[project.scripts]
streamlit-deck = "streamlit_deck.cli:run"

[project]
name = "streamlit-deck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyautogui>=0.9.54",
    "streamlit>=1.54.0",
]
