[theme]
base = "dark"
font = "'IBM Plex Mono':https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500;600;700&display=swap"
primaryColor = "#ff0000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#ffffff"
borderColor = "#333333"
